# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- feature

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:

    - script: |
        sudo apt-get update && sudo apt-get install -y maven
        mvn clean install
      displayName: 'Maven build'

    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        containerRegistry: 'TempDockerRegistry'
        command: 'login'

    - task: Docker@2
      inputs:
        containerRegistry: 'ACRConn'
        repository: 'riaoct30/tomcat-test'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
      retryCountOnTaskFailure: '1'

    # - task: Docker@2
    #   displayName: 'Build and Push Docker Image'
    #   inputs:
    #     containerRegistry: 'TempDockerRegistry'
    #     repository: 'riaoct30/tomcat-test'
    #     command: buildAndPush
    #     Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #   retryCountOnTaskFailure: '1'
#      inputs: 
#        containerRegistry: 'TempDockerRegistry'
#        repository: 'riaoct30/tomcat8-java-webapp'
#        command: push
#        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'



    #- task: Maven@4
    #  inputs:
    #    mavenPomFile: 'pom.xml'
    #    publishJUnitResults: true
    #    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    #    javaHomeOption: 'JDKVersion'
    #    mavenVersionOption: 'Default'
    #    mavenAuthenticateFeed: false
    #    effectivePomSkip: false
    #    sonarQubeRunAnalysis: false
    #- task: Docker@2
    #  displayName: Build an image
    #  inputs:
    #    command: build
    #    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    #    tags: |
    #    command: start
    #    container: test-1
