name: Java CI with Maven

on:
  push:

jobs:
  maven_build:
    strategy:
      matrix:
        version: [11, 8]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: "${{ matrix.version }}"
        distribution: 'temurin'
        cache: maven
    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-cache
    - name: Build with Maven
      run: mvn -B package --file pom.xml
