name: Maven Build CI/CD Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    uses: anujdevopslearn/GithubActionsWorkflows/.github/workflows/maven.yml@main
    with:
      build-script: pom.xml

  deploy:
    needs: build
    uses: anujdevopslearn/GithubActionsWorkflows/.github/workflows/tomcat.yml@main
    secrets:
       host: ${{ secrets.DC_HOST }}
       user: ${{ secrets.DC_USER }}
       password: ${{ secrets.DC_KEY }}
